POST http://localhost:8080/users/login

{
 "Email":"bob@gmail.com", 
 "Password":"test1234"
}
###
POST http://localhost:8080/users/login

{
  "Email":"john.doe@gmail.com", 
  "Password":"test1234"
}
###
POST http://localhost:8080/users/signup

{ 
 "Username":"john",            
 "Name":"John",            
 "Email":"john.doe@gmail.com", 
 "Password":"test1234",
 "User_type":"USER"
 }

POST http://localhost:8080/users/signup
###
{ 
 "Username":"bob12",            
 "Name":"Bob Smith",            
 "Email":"bob@gmail.com", 
 "Password":"test1234",
 "User_type":"ADMIN"
}
###
GET http://localhost:8080/users/6796785f6f88ed2b75e1a2c2
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJOYW1lIjoiQm9iIFNtaXRoIiwiVXNlcm5hbWUiOiJib2IxMiIsIlVpZCI6IjY3OTZiMDY3MTI1M2Q1NjI5ZjM4YzY0YyIsIlVzZXJfdHlwZSI6IkFETUlOIiwiZXhwIjoxNzM5MDUyNDgzfQ.KUX6PEw-2cwvu7ShOu2syCe2KzLDoxwF-sZaYt3Cbqw
###
GET http://localhost:8080/users
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJOYW1lIjoiQm9iIFNtaXRoIiwiVXNlcm5hbWUiOiJib2IxMiIsIlVpZCI6IjY3OTZiMDY3MTI1M2Q1NjI5ZjM4YzY0YyIsIlVzZXJfdHlwZSI6IkFETUlOIiwiZXhwIjoxNzM5MDUyNDgzfQ.KUX6PEw-2cwvu7ShOu2syCe2KzLDoxwF-sZaYt3Cbqw
###
POST http://localhost:8080/genres
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJOYW1lIjoiQm9iIFNtaXRoIiwiVXNlcm5hbWUiOiJib2IxMiIsIlVpZCI6IjY3OTZiMDY3MTI1M2Q1NjI5ZjM4YzY0YyIsIlVzZXJfdHlwZSI6IkFETUlOIiwiZXhwIjoxNzM5MDUyNDgzfQ.KUX6PEw-2cwvu7ShOu2syCe2KzLDoxwF-sZaYt3Cbqw

{
 "Name":"Animation",
 "genre_id":2
}
###
GET http://localhost:8080/genres/2
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJOYW1lIjoiQm9iIFNtaXRoIiwiVXNlcm5hbWUiOiJib2IxMiIsIlVpZCI6IjY3OTZiMDY3MTI1M2Q1NjI5ZjM4YzY0YyIsIlVzZXJfdHlwZSI6IkFETUlOIiwiZXhwIjoxNzM5MDUyNDgzfQ.KUX6PEw-2cwvu7ShOu2syCe2KzLDoxwF-sZaYt3Cbqw
###
GET http://localhost:8080/genres
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJOYW1lIjoiQm9iIFNtaXRoIiwiVXNlcm5hbWUiOiJib2IxMiIsIlVpZCI6IjY3OTZiMDY3MTI1M2Q1NjI5ZjM4YzY0YyIsIlVzZXJfdHlwZSI6IkFETUlOIiwiZXhwIjoxNzM5MDUyNDgzfQ.KUX6PEw-2cwvu7ShOu2syCe2KzLDoxwF-sZaYt3Cbqw
###
POST http://localhost:8080/genres
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJOYW1lIjoiQm9iIFNtaXRoIiwiVXNlcm5hbWUiOiJib2IxMiIsIlVpZCI6IjY3OTZiMDY3MTI1M2Q1NjI5ZjM4YzY0YyIsIlVzZXJfdHlwZSI6IkFETUlOIiwiZXhwIjoxNzM5MDUyNDgzfQ.KUX6PEw-2cwvu7ShOu2syCe2KzLDoxwF-sZaYt3Cbqw

{
 "Name":"Test1",
 "genre_id":3
}
###
PUT http://localhost:8080/genres/679c041e4d5af5c57140481f
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJOYW1lIjoiQm9iIFNtaXRoIiwiVXNlcm5hbWUiOiJib2IxMiIsIlVpZCI6IjY3OTZiMDY3MTI1M2Q1NjI5ZjM4YzY0YyIsIlVzZXJfdHlwZSI6IkFETUlOIiwiZXhwIjoxNzM5MDUyNDgzfQ.KUX6PEw-2cwvu7ShOu2syCe2KzLDoxwF-sZaYt3Cbqw

{
 "Name":"Test",
  "genre_id":3
}
###
DELETE http://localhost:8080/genres/3
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJOYW1lIjoiQm9iIFNtaXRoIiwiVXNlcm5hbWUiOiJib2IxMiIsIlVpZCI6IjY3OTZiMDY3MTI1M2Q1NjI5ZjM4YzY0YyIsIlVzZXJfdHlwZSI6IkFETUlOIiwiZXhwIjoxNzM5MDUyNDgzfQ.KUX6PEw-2cwvu7ShOu2syCe2KzLDoxwF-sZaYt3Cbqw
###
POST http://localhost:8080/movies
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJOYW1lIjoiQm9iIFNtaXRoIiwiVXNlcm5hbWUiOiJib2IxMiIsIlVpZCI6IjY3OTZiMDY3MTI1M2Q1NjI5ZjM4YzY0YyIsIlVzZXJfdHlwZSI6IkFETUlOIiwiZXhwIjoxNzM5MDUyNDgzfQ.KUX6PEw-2cwvu7ShOu2syCe2KzLDoxwF-sZaYt3Cbqw

{
	"Name":"Rango",
	"Topic":"test",
	"genre_id":2,
	"Movie_URL":"test.com",
	"movie_id":1
}
###
GET http://localhost:8080/movies/67a678329b4f9929e019bb9c
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJOYW1lIjoiQm9iIFNtaXRoIiwiVXNlcm5hbWUiOiJib2IxMiIsIlVpZCI6IjY3OTZiMDY3MTI1M2Q1NjI5ZjM4YzY0YyIsIlVzZXJfdHlwZSI6IkFETUlOIiwiZXhwIjoxNzM5MDUyNDgzfQ.KUX6PEw-2cwvu7ShOu2syCe2KzLDoxwF-sZaYt3Cbqw
###
GET http://localhost:8080/movies
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJOYW1lIjoiQm9iIFNtaXRoIiwiVXNlcm5hbWUiOiJib2IxMiIsIlVpZCI6IjY3OTZiMDY3MTI1M2Q1NjI5ZjM4YzY0YyIsIlVzZXJfdHlwZSI6IkFETUlOIiwiZXhwIjoxNzM5MDUyNDgzfQ.KUX6PEw-2cwvu7ShOu2syCe2KzLDoxwF-sZaYt3Cbqw
###
PUT http://localhost:8080/movies/67a67da765b7aa6b11fac961
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJOYW1lIjoiQm9iIFNtaXRoIiwiVXNlcm5hbWUiOiJib2IxMiIsIlVpZCI6IjY3OTZiMDY3MTI1M2Q1NjI5ZjM4YzY0YyIsIlVzZXJfdHlwZSI6IkFETUlOIiwiZXhwIjoxNzM5MDUyNDgzfQ.KUX6PEw-2cwvu7ShOu2syCe2KzLDoxwF-sZaYt3Cbqw

{
	"Name":"Hello",
	"Topic":"hey",
	"genre_id":2,
	"Movie_URL":"test1.com"
}

###
GET http://localhost:8080/movies/search?name=Ra
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJOYW1lIjoiQm9iIFNtaXRoIiwiVXNlcm5hbWUiOiJib2IxMiIsIlVpZCI6IjY3OTZiMDY3MTI1M2Q1NjI5ZjM4YzY0YyIsIlVzZXJfdHlwZSI6IkFETUlOIiwiZXhwIjoxNzM5MDUyNDgzfQ.KUX6PEw-2cwvu7ShOu2syCe2KzLDoxwF-sZaYt3Cbqw

###
GET http://localhost:8080/movies/filter?genre_id=1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJOYW1lIjoiQm9iIFNtaXRoIiwiVXNlcm5hbWUiOiJib2IxMiIsIlVpZCI6IjY3OTZiMDY3MTI1M2Q1NjI5ZjM4YzY0YyIsIlVzZXJfdHlwZSI6IkFETUlOIiwiZXhwIjoxNzM5MDUyNDgzfQ.KUX6PEw-2cwvu7ShOu2syCe2KzLDoxwF-sZaYt3Cbqw
###
DELETE http://localhost:8080/movies/3
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJOYW1lIjoiQm9iIFNtaXRoIiwiVXNlcm5hbWUiOiJib2IxMiIsIlVpZCI6IjY3OTZiMDY3MTI1M2Q1NjI5ZjM4YzY0YyIsIlVzZXJfdHlwZSI6IkFETUlOIiwiZXhwIjoxNzM5MDUyNDgzfQ.KUX6PEw-2cwvu7ShOu2syCe2KzLDoxwF-sZaYt3Cbqw
###
POST http://localhost:8080/reviews
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImpvaG4uZG9lQGdtYWlsLmNvbSIsIk5hbWUiOiJKb2huIiwiVXNlcm5hbWUiOiJqb2huIiwiVWlkIjoiNjc5Njc4NWY2Zjg4ZWQyYjc1ZTFhMmMyIiwiVXNlcl90eXBlIjoiVVNFUiIsImV4cCI6MTczOTA1MzMzMH0.eQYXoLRyjWwjp6HdJdv4vAG4M_K2TE6R4Bq7VlMBvDU

{
	"review" : "Best",
	"movie_id" : 1,
	"review_id": 1,
	"reviewer_id" : "6796785f6f88ed2b75e1a2c2" 
}
###
POST http://localhost:8080/reviews
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImpvaG4uZG9lQGdtYWlsLmNvbSIsIk5hbWUiOiJKb2huIiwiVXNlcm5hbWUiOiJqb2huIiwiVWlkIjoiNjc5Njc4NWY2Zjg4ZWQyYjc1ZTFhMmMyIiwiVXNlcl90eXBlIjoiVVNFUiIsImV4cCI6MTczOTA1MzMzMH0.eQYXoLRyjWwjp6HdJdv4vAG4M_K2TE6R4Bq7VlMBvDU

{
	"review" : "Average",
	"movie_id" : 2,
	"review_id": 2,
	"reviewer_id" : "6796785f6f88ed2b75e1a2c2" 
}
###
GET http://localhost:8080/reviews/filter?movie_id=1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImpvaG4uZG9lQGdtYWlsLmNvbSIsIk5hbWUiOiJKb2huIiwiVXNlcm5hbWUiOiJqb2huIiwiVWlkIjoiNjc5Njc4NWY2Zjg4ZWQyYjc1ZTFhMmMyIiwiVXNlcl90eXBlIjoiVVNFUiIsImV4cCI6MTczOTA1MzMzMH0.eQYXoLRyjWwjp6HdJdv4vAG4M_K2TE6R4Bq7VlMBvDU
###
DELETE http://localhost:8080/reviews/67a73063242bb93392c92e0d
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImpvaG4uZG9lQGdtYWlsLmNvbSIsIk5hbWUiOiJKb2huIiwiVXNlcm5hbWUiOiJqb2huIiwiVWlkIjoiNjc5Njc4NWY2Zjg4ZWQyYjc1ZTFhMmMyIiwiVXNlcl90eXBlIjoiVVNFUiIsImV4cCI6MTczOTA1MzMzMH0.eQYXoLRyjWwjp6HdJdv4vAG4M_K2TE6R4Bq7VlMBvDU
###
GET http://localhost:8080/reviews/user/6796785f6f88ed2b75e1a2c2
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImpvaG4uZG9lQGdtYWlsLmNvbSIsIk5hbWUiOiJKb2huIiwiVXNlcm5hbWUiOiJqb2huIiwiVWlkIjoiNjc5Njc4NWY2Zjg4ZWQyYjc1ZTFhMmMyIiwiVXNlcl90eXBlIjoiVVNFUiIsImV4cCI6MTczOTA1MzMzMH0.eQYXoLRyjWwjp6HdJdv4vAG4M_K2TE6R4Bq7VlMBvDU
